# Generated by Django 5.0.1 on 2025-09-12 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entregas", "0003_solicitacao_delete_entrega"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="solicitacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas",
                to="app_entregas.solicitacao",
            ),
        ),
    ]
