# Generated by Django 5.0.1 on 2025-09-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaEPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Categoria de EPI",
                "verbose_name_plural": "Categorias de EPI",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "tamanho",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                            ("U", "Único"),
                        ],
                        max_length=3,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epis",
                        to="app_epis.categoriaepi",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
