# Generated by Django 5.2.5 on 2025-09-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_epis", "0003_epi_epi_estoque_nao_negativo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="epi",
            constraint=models.CheckConstraint(
                condition=models.Q(("estoque_minimo__gte", 0)),
                name="epi_estoque_minimo_nao_negativo",
            ),
        ),
    ]
