# Generated by Django 5.0.1 on 2025-09-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_colaboradores", "0002_rename_criado_em_colaborador_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colaborador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
