# Generated by Django 5.0.1 on 2025-09-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_colaboradores",
            "0004_rename_updated_at_colaborador_atualizado_em_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colaborador",
            options={},
        ),
    ]
